### PR TITLE
Weapon traits update

### PR DESCRIPTION
**Pull request by JFranklin3000**
Added GI Joe, TF and Across the Stars Weapon and Armor Traits, and the Light Weapon Type.

### CODE REVIEW

**Comment by phildominguez** [comment]
image
You'll want to `white-space: nowrap;` these

**Comment by JFranklin3000** [comment]
fixed the word wrap. Although that list of checkboxes is on my list to make go away as well.

**Review by phildominguez — APPROVED** [review]
💯

**Review by guswadsworth12 — APPROVED** [review]
Effects work well and look great

**Pull request merged**
